# -*- coding: utf-8 -*-
"""指标层公开入口（含预算调仓模拟）。"""
from __future__ import annotations

from .ads import (  # noqa: F401
    INDICATOR_SPECS,
    Number,
    attributed_rate,
    bid_consistency_gap,
    build_metrics,
    cpa,
    cpa_from_cpc,
    cpc,
    cpc_from_cpm,
    cpm,
    cpm_from_cpc,
    cost_concentration,
    ctr,
    cvr,
    ecpm_from_funnel,
    gini,
    hhi,
    ipv,
    relative_change,
    safe_div,
    target_cpa_from_ecpm,
    top_k_share,
    zscore,
)
from .aggregate import (  # noqa: F401
    DIMENSION_FIELDS,
    aggregate,
    campaign_table,
    daily_totals,
    dimension_tables,
    hourly_totals,
    overall_totals,
)
from .allocation import simulate_reallocation  # noqa: F401

__all__ = [
    "DIMENSION_FIELDS",
    "INDICATOR_SPECS",
    "Number",
    "aggregate",
    "attributed_rate",
    "bid_consistency_gap",
    "build_metrics",
    "campaign_table",
    "cpa",
    "cpa_from_cpc",
    "cpc",
    "cpc_from_cpm",
    "cpm",
    "cpm_from_cpc",
    "cost_concentration",
    "ctr",
    "cvr",
    "daily_totals",
    "dimension_tables",
    "ecpm_from_funnel",
    "gini",
    "hhi",
    "hourly_totals",
    "ipv",
    "overall_totals",
    "relative_change",
    "safe_div",
    "simulate_reallocation",
    "target_cpa_from_ecpm",
    "top_k_share",
    "zscore",
]
